import { SustainabilityAction } from '@/types';

export const PREDEFINED_ACTIONS: SustainabilityAction[] = [
  {
    id: 'no-car-day',
    name: 'No Car Day',
    description: 'Commuted without using a personal car',
    icon: '🚗',
    category: 'transport',
    impactMetrics: {
      co2Kg: 4.6,
      waterLiters: 0,
      energyKwh: 0,
      treesEquivalent: 0.21,
    },
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'meatless-meal',
    name: 'Meatless Meal',
    description: 'Enjoyed a plant-based meal instead of meat',
    icon: '🥗',
    category: 'food',
    impactMetrics: {
      co2Kg: 2.5,
      waterLiters: 1500,
      energyKwh: 0.5,
      treesEquivalent: 0.11,
    },
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'shorter-shower',
    name: 'Shorter Shower',
    description: 'Reduced shower time by 5 minutes',
    icon: '🚿',
    category: 'water',
    impactMetrics: {
      co2Kg: 0.5,
      waterLiters: 40,
      energyKwh: 1.5,
      treesEquivalent: 0.02,
    },
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'line-dry',
    name: 'Line Dry Clothes',
    description: 'Air dried laundry instead of using dryer',
    icon: '👕',
    category: 'energy',
    impactMetrics: {
      co2Kg: 2.4,
      waterLiters: 0,
      energyKwh: 3.0,
      treesEquivalent: 0.11,
    },
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bike-commute',
    name: 'Bike Commute',
    description: 'Cycled instead of driving',
    icon: '🚴',
    category: 'transport',
    impactMetrics: {
      co2Kg: 4.6,
      waterLiters: 0,
      energyKwh: 0,
      treesEquivalent: 0.21,
    },
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'reusable-container',
    name: 'Reusable Container',
    description: 'Used reusable container instead of disposable',
    icon: '🥡',
    category: 'waste',
    impactMetrics: {
      co2Kg: 0.1,
      waterLiters: 10,
      energyKwh: 0.05,
      treesEquivalent: 0.005,
    },
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'public-transport',
    name: 'Public Transport',
    description: 'Used bus, train, or subway instead of car',
    icon: '🚌',
    category: 'transport',
    impactMetrics: {
      co2Kg: 3.0,
      waterLiters: 0,
      energyKwh: 0,
      treesEquivalent: 0.14,
    },
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'local-produce',
    name: 'Local Produce',
    description: 'Bought locally sourced food',
    icon: '🍎',
    category: 'food',
    impactMetrics: {
      co2Kg: 1.0,
      waterLiters: 100,
      energyKwh: 0.3,
      treesEquivalent: 0.05,
    },
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'unplugged-devices',
    name: 'Unplugged Devices',
    description: 'Unplugged electronics when not in use',
    icon: '🔌',
    category: 'energy',
    impactMetrics: {
      co2Kg: 0.3,
      waterLiters: 0,
      energyKwh: 0.5,
      treesEquivalent: 0.01,
    },
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'reusable-bag',
    name: 'Reusable Bag',
    description: 'Used reusable shopping bags',
    icon: '🛍️',
    category: 'waste',
    impactMetrics: {
      co2Kg: 0.2,
      waterLiters: 20,
      energyKwh: 0.1,
      treesEquivalent: 0.01,
    },
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cold-wash',
    name: 'Cold Water Wash',
    description: 'Washed clothes in cold water',
    icon: '🧺',
    category: 'energy',
    impactMetrics: {
      co2Kg: 0.6,
      waterLiters: 0,
      energyKwh: 0.8,
      treesEquivalent: 0.03,
    },
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'composted',
    name: 'Composted',
    description: 'Composted food scraps instead of trashing',
    icon: '🌱',
    category: 'waste',
    impactMetrics: {
      co2Kg: 0.4,
      waterLiters: 5,
      energyKwh: 0,
      treesEquivalent: 0.02,
    },
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
];

export const CATEGORY_INFO: Record<string, { label: string; color: string; bgColor: string }> = {
  transport: { label: 'Transport', color: 'text-blue-600', bgColor: 'bg-blue-100' },
  food: { label: 'Food', color: 'text-green-600', bgColor: 'bg-green-100' },
  energy: { label: 'Energy', color: 'text-amber-600', bgColor: 'bg-amber-100' },
  water: { label: 'Water', color: 'text-cyan-600', bgColor: 'bg-cyan-100' },
  waste: { label: 'Waste', color: 'text-purple-600', bgColor: 'bg-purple-100' },
  other: { label: 'Other', color: 'text-gray-600', bgColor: 'bg-gray-100' },
};

export const ACTION_ICONS = ['🚗', '🚴', '🚌', '🚶', '🥗', '🍎', '🥡', '🚿', '💧', '🔌', '💡', '👕', '🧺', '🌱', '♻️', '🛍️', '🌍', '🌿', '☀️', '🌊'];
